### PR TITLE
Deleted Nadva.qml and added initial commit for the wayland compositor

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by MrSerge01 — APPROVED** [review]
LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

LGTM!!!!!!!!!11111111111111111111111111

**Review by StoneMcYT — COMMENTED** [review]
Dont see why main.rs is needed but everything else seems fine

**Review by Sammy99jsp — APPROVED** [review]
Looks good,
What about using the git version of smithay?

**Comment by ghost** [comment]
Sure 👍🏿

**Review by Froxcey — COMMENTED** [review]
Ok yeah this is the initial commit... Great job guys!

**Pull request merged**
