### PR TITLE
Deleted unnecessary Compositor folder

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MrSerge01** [comment]
bruh why delete
the compositor folder is linked to a compositor repository
so when someone does a pull request to it here and it gets merged it syncs on 2 repos at the same time

**Comment by MrSerge01** [comment]
so if this gets merged, the compositor repo's cargo and main will get deleted

**Comment by ghost** [comment]
Hehe

**Comment by MrSerge01** [comment]
im stupid, i am dumb, i am dumbest

Froxcey agreed even

**Comment by ghost** [comment]
No

**Comment by ghost** [comment]
Merge this cmon don't say that ur stupid

**Review by MrSerge01 — APPROVED** [review]
LGTM,
-The Stoopid Goos.

**Comment by ghost** [comment]
Coolness

**Pull request merged**
