### PR TITLE
Updated Login Screen Icons

### PR DESCRIPTION
**Pull request by SEGPlayz**

### CODE REVIEW

**Comment by SEGPlayz** [comment]
ANYONE,,,,, PLS REVIEW THIS

**Comment by Sammy99jsp** [comment]
Jeez, chill. I think Froxcey's gone to bed and Pigpot's on holiday rn.
Soz dude, you may have to wait until one of them is up. I'll add Froxcey as a reviewer though.

**Comment by Froxcey** [comment]
Okay yeah I should probably also handle this repo, imma review

**Review by Froxcey — CHANGES_REQUESTED** [review]
forward.svg doesn't really work...

**Comment by StoneMcYT** [comment]
image
Hmm not full circles?

**Review by SEGPlayz — COMMENTED** [review]
Fixed

**Review by kerichdev — COMMENTED** [review]
settings and others are still broken

**Comment by SEGPlayz** [comment]
what is it the circles?

**Comment by kerichdev** [comment]
image
yes

ed: actually all of them are broken lmao

**Comment by SEGPlayz** [comment]
Now Fixed https://github.com/Avdan-OS/Desktop-Environment/pull/50

**Pull request closed without merging**
