### PR TITLE
Updated some words

### PR DESCRIPTION
**Pull request by Rohith0009**
^Title

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Why deleting these words?

**Comment by Froxcey** [comment]
... does not follow a space. Oof is indeed informal, but that doesn't mean we can't use it. "Think so" is completely fine, no need to change it.

**Comment by Rohith0009** [comment]
> Why deleting these words?

Oof is a informal word it sound good but is won't be good in such a huge Project

**Comment by Rohith0009** [comment]
> ... does not follow a space. Oof is indeed informal, but that doesn't mean we can't use it. "Think so" is completely fine, no need to change it.

Ok I will remove a space. But I think oof does not make sense in this project

**Comment by Froxcey** [comment]
How about "think so"

**Comment by Rohith0009** [comment]
> How about "think so"

ok then I will close this pr

**Review by ghost — APPROVED** [review]

**Pull request merged**
