### PR TITLE
Updated for rust

### PR DESCRIPTION
**Pull request by dxvv-software**

### CODE REVIEW

**Review by avataat — APPROVED** [review]

**Comment by ghost** [comment]
Mmh qml are u sure?

**Comment by TechStudent10** [comment]
> Mmh qml are u sure?

They changed the README to say Rust instead of QML.

**Review by TechStudent10 — APPROVED** [review]
LGTM

**Review by Froxcey — COMMENTED** [review]
WM is made using Rust and Smithay. The rest can be in c++ but we might just go full Rusty as well. This sentence sounds kinda weird, it sounds like everything is made with Rust + Qt working together when it's actually not related at all (at least as of now). I would say having the full tech stack written out would be better.

**Review by TechStudent10 — COMMENTED** [review]
Oops I didn't notice that it said "and Rust" not just "Rust". I don't think we are using Qt and QML for the DE anymore.

**Comment by dxvv-software** [comment]
> > Mmh qml are u sure?
> 
> They changed the README to say Rust instead of QML.

I'm not gay so he

**Comment by TechStudent10** [comment]
> > > Mmh qml are u sure?
> > 
> > 
> > They changed the README to say Rust instead of QML.
> 
> I'm not gay so he

????????? What?

**Comment by Froxcey** [comment]
> I'm not gay so he

"They/them" is a gender neutral term, not gay. "They/them" can be used to refer to both non binary and unknown gender, as in you didn't write it in your bio so ppl use they instead of guessing and then misgender. Thank you for clarifying your gender, but "they/them" definitely works in this case, as it is specifically made to not misgender someone when gender expression is not shown. Also, maybe put "he/him" in your bio, that way everyone can see.

**Comment by TechStudent10** [comment]
> > I'm not gay so he
> 
> "They/them" is a gender neutral term, not gay. "They/them" can be used to refer to both non binary and unknown gender, as in you didn't write it in your bio so ppl use they instead of guessing and then misgender. Thank you for clarifying your gender, but "they/them" definitely works in this case, as it is specifically made to not misgender someone when gender expression is not shown. Also, maybe put "he/him" in your bio, that way everyone can see.

Ohhhhhhh that. Yeah I didn't want to guess so I put they.

**Comment by dxvv-software** [comment]
ok the convo changed from its original meaning

**Comment by MrSerge01** [comment]
> ok the convo changed from its original meaning

of course it will lmfao

**Comment by dxvv-software** [comment]
just merge

**Comment by ghost** [comment]
> just merge

No you have to delete all qml refs in the readme

**Comment by dxvv-software** [comment]
> > just merge
> 
> No you have to delete all qml refs in the readme

I will do that

**Review by dxvv-software — COMMENTED** [review]
i removed QML

**Review by ghost — APPROVED** [review]

**Comment by dxvv-software** [comment]
thanks

**Comment by Trynera** [comment]
> > ok the convo changed from its original meaning
> 
> of course it will lmfao

Goos

**Comment by dxvv-software** [comment]
> > > ok the convo changed from its original meaning
> > 
> > 
> > of course it will lmfao
> 
> Goos

yes. its goos

**Comment by MrSerge01** [comment]
> > > ok the convo changed from its original meaning
> > 
> > of course it will lmfao
> 
> Goos

classic goos's behaviour

**Pull request merged**
